### ISSUE TITLE
Unable to add additional plugins? 

### ISSUE THREAD

**Issue by TweakGames** [WatchBeam/obs-studio-ftl#52]
Hello, 

I am trying to install the "obs-websocket - Websocket API for OBS Studio 0.3.2" from https://obsproject.com/forum/resources/obs-websocket-websocket-api-for-obs-studio.466/ 

It works properly in normal OBS, but fails in OBS-FTL with the error,:

The procedure entry point
?channelReadyRead@QIODevice@@QEAAXH@z could not be located in the dynamic link library c:\Program Files (x86)\OBS Studio - FTL\obs-plugins\64bit\Qt5Network.dll.  

That file is there, but I was wondering if maybe all plugins are disabled on this beta OBS-FTL right now? 

Thanks.

**Comment by Maximilian-Reuter** [comment]
this seems to be the case since obs ftl is still being compiled with qt 5.6.2 instead of 5.7 . Paging @sslivins could you change that ?

**Comment by hamatzu** [comment]
I am facing this exact issue as well. Would it be possible to get a build compiled for qt 5.7?

Thanks!

**Comment by digitronics** [comment]
These instructions work for building from source if you wanna check them out https://github.com/jp9000/obs-studio/wiki/Install-Instructions#windows-build-directions just set the `QTDIR`  to 5.8, I haven't run into any issues from building it with Qt 5.8

**Comment by QuinnDamerell** [comment]
This has been resolved, the newest version is using QT 5.8, which is what OBS 18 uses.

**Comment by Palakis** [comment]
@QuinnDamerell Where did you got the info that OBS 18 is built with Qt 5.8 ?

obs-websocket is built with Qt 5.7.0 and works perfectly in OBS Studio 18.0 and 18.0.1. But OBS FTL 18.0 doesn't start with obs-websocket installed.
This can be the sign of a version mismatch between OBS FTL's `Qt5Core.dll` and the `Qt5Core.dll` expected by `Qt5Network.dll` and `Qt5WebSockets.dll` embedded with obs-websocket releases.
And that's why I believe OBS Studio 18.0 and 18.0.1 are built with [Qt 5.7.0](https://download.qt.io/official_releases/qt/5.7/5.7.0/).

**Comment by hamatzu** [comment]
I can confirm it's still NOT possible to install the obs-websocket plugin with the obs-ftl branch, but it's still possible to use it with the original build, as @palakis says.

**Comment by Palakis** [comment]
On a side note, please note that plugins which do not depend on Qt (like the stinger transition) are not affected by this Qt version mismatch.

**Comment by z4kk** [comment]
I still had that problem in version OBS-Studio 18.0.1 with FTL 0.9.4: https://github.com/Palakis/obs-websocket/issues/57

**Comment by Maximilian-Reuter** [comment]
@QuinnDamerell newest obs is definitely still using qt 5.7 

![image](https://cloud.githubusercontent.com/assets/5833783/24578335/eff7fab2-16de-11e7-97c1-78dd90d60018.png)
